# generated by datamodel-codegen:
#   filename:  topology.schema.json
#   timestamp: 2022-01-09T14:03:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import BaseModel, Extra, Field, conint, constr


class Type(Enum):
    TopologyConfiguration = 'TopologyConfiguration'


class Ipv4Address(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str


class Ipv6Address(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str


class Ipv4Interface(BaseModel):
    class Config:
        extra = Extra.forbid

    address: Ipv4Address
    subnet: str
    gateway: Ipv4Address


class Ipv6Interface(BaseModel):
    class Config:
        extra = Extra.forbid

    address: Ipv6Address
    subnet: str
    gateway: Ipv6Address


class Type1(Enum):
    ethernet = 'ethernet'
    virtual = 'virtual'
    loopback = 'loopback'
    child = 'child'


class Type2(Enum):
    bridge = 'bridge'


class TransitItem(BaseModel):
    name: Optional[str] = None
    asn: Optional[int] = None
    remote: Optional[List[Union[Ipv4Address, Ipv6Address]]] = None


class BgpConfiguration(BaseModel):
    transit: Optional[List[TransitItem]] = Field(None, title='Transit')


class OspfConfiguration(BaseModel):
    __root__: Any = Field(
        ...,
        description='Represents the ospf configuration of a device',
        title='OSPF Configuration',
    )


class Connection(BaseModel):
    hostname: constr(max_length=255)
    port: Optional[constr(max_length=255)] = None


class Routing(BaseModel):
    bgp: Optional[BgpConfiguration] = None
    ospf: Optional[OspfConfiguration] = None


class InterfaceConfiguration(BaseModel):
    name: constr(max_length=20)
    description: constr(max_length=255)
    mac: Optional[
        constr(regex=r'^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$', max_length=17)
    ] = None
    mtu: Optional[conint(ge=576, le=9216)] = None
    speed: Optional[conint(ge=0, le=1000000000)] = None
    enabled: Optional[bool] = True
    connected_to: Optional[Connection] = Field(
        None, description='The name of the interface this interface is connected to'
    )
    addresses: Optional[List[Union[Ipv4Address, Ipv6Address]]] = Field(
        None, title='Addresses'
    )


class NetworkInterface(InterfaceConfiguration):
    type: Optional[Type1] = None


class BridgeInterface(InterfaceConfiguration):
    type: Optional[Type2] = None
    bridge_members: Optional[List[NetworkInterface]] = Field(
        None, title='Bridge Members'
    )


class JsonSchemaForTopologyConfiguration(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Type
    interfaces: Optional[List[Union[NetworkInterface, BridgeInterface]]] = Field(
        None, title='Interfaces'
    )
    routing: Optional[Union[List, Routing]] = Field(None, title='Routing')
