@startuml name Git as Source of Truth

!theme bluegray
skinparam DefaultTextAlignment center
skinparam BackgroundColor White
skinparam Dpi 100

' node RESTAPI as "REST API"
component Syncer as "NetBox sync"
node NetBox
' node Topology as "Topology\nMaker"
node eve
component Repository as "Git Repository"
node Runner
node NetworkDevice as "Network Device"
component JsonSchema
actor Admin


' RESTAPI --> JsonSchema
' RESTAPI -right-> Repository
Repository -up-> Syncer
Syncer -up-> NetBox
' Topology -up-> RESTAPI
' Admin -right-> Topology: views\ntopology diagrams
eve -down-> Repository: generates device-specific\nconfigurations from\nthe data model
eve -right-> JsonSchema: verifies config
Admin -down--> eve
Admin -down-> JsonSchema: must follow\ndata model
Admin -down-> Repository: creates\nconfiguration changes
' Admin -down-> RESTAPI: uses\nquery tools
Admin -left-> NetBox: read only\naccess
Runner -down-> Repository: retrieves\nconfiguration changes
Runner -down-> NetworkDevice: applies\nconfiguration changes
@enduml
